import http from 'node:http';
import fs from 'node:fs';
import {Store} from './store.mjs';
function readJsonSafe(p){try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{return null;}}
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Arcade Decisions • Paper Laboratory</title><style>
:root{color-scheme:dark;--bg:#0b1014;--panel:#151c21;--muted:#8b9ba5;--line:#2c373e;--accent:#d4f176}*{box-sizing:border-box}body{font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:#e5eef3;padding:28px;max-width:1180px;margin:auto}h1{font-size:30px;letter-spacing:-1px;margin:0}h2{font-size:17px}small,p{color:var(--muted)}small{display:block}.tag{display:inline-block;border:1px solid var(--line);color:var(--accent);border-radius:20px;padding:5px 10px;font-size:12px;margin-bottom:12px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:26px 0}.card{background:var(--panel);border:1px solid var(--line);border-radius:15px;padding:18px}.n{font-size:28px;font-weight:700;color:var(--accent)}table{border-collapse:collapse;width:100%;font-size:13px;min-width:670px}td,th{text-align:left;padding:11px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}.tablewrap{overflow:auto}.foot{margin-top:30px;font-size:12px}strong{color:#e5eef3}.muted{color:var(--muted)}.ok{color:var(--accent)}
</style></head><body><span class="tag">NO REAL MONEY • NO TRANSACTION EXECUTION</span><h1>Arcade Decisions</h1><p>BTC · Jupiter-only observations · OpenAI / Jev / GLiDE · independent paper benchmark</p><section class="cards" id="counts"></section><h2>Source health (Jupiter read-only)</h2><section class="cards" id="health"></section><h2>Independent model arms</h2><section class="cards" id="arms"></section><h2>Venue rounds (official settlement truth)</h2><div class="tablewrap"><table><thead><tr><th>Round</th><th>Status</th><th>Outcome</th><th>Openµ</th><th>Closeµ</th><th>UP pool</th><th>DOWN pool</th></tr></thead><tbody id="venue"></tbody></table></div><h2>Research status (read-only)</h2><section class="cards" id="research"></section><h2>Recent decisions</h2><div class="tablewrap"><table><thead><tr><th>Round</th><th>Model</th><th>Status</th><th>P(UP)</th><th>Paper action</th><th>Result</th><th>Correct</th></tr></thead><tbody id="rows"></tbody></table></div><p class="foot">Virtual PnL is intentionally unavailable until pre-lock pool odds and fee mechanics are independently verified. Uncalibrated model scores are not win probabilities. This dashboard never submits bets. <span id="time"></span></p><script>
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>Number(x||0).toLocaleString();
async function load(){try{const x=await(await fetch('/api/stats',{cache:'no-store'})).json();if(x.demoMode){document.getElementById('time').textContent='SYNTHETIC FIXTURE ONLY · Not real providers or Jupiter rounds.';}document.getElementById('counts').innerHTML=[['Observed rounds',x.counts.rounds],['Jupiter price ticks',x.counts.ticks],['Frozen snapshots',x.counts.snapshots],['Pool observations',x.counts.poolObs||0]].map(y=>'<div class="card"><small>'+esc(y[0])+'</small><div class="n">'+n(y[1])+'</div></div>').join('');
document.getElementById('health').innerHTML=[['Ticks last 5m',x.tickHealth?x.tickHealth.n5m:0],['Last tick age',x.tickHealth&&x.tickHealth.lastMs?Math.max(0,Math.round((Date.now()-x.tickHealth.lastMs)/1000))+'s ago':'no ticks'],['Clock drift',x.clock?Math.round(x.clock.driftMs)+' ms':'unknown']].map(y=>'<div class="card"><small>'+esc(y[0])+'</small><div class="n" style="font-size:22px">'+esc(y[1])+'</div></div>').join('');
document.getElementById('venue').innerHTML=(x.venueRounds||[]).map(v=>'<tr>'+[v.id,v.status,v.outcome,v.openPrice,v.closePrice,v.upPool,v.downPool].map(y=>'<td>'+esc(y)+'</td>').join('')+'</tr>').join('');
document.getElementById('arms').innerHTML=x.arms.map(a=>'<div class="card"><strong>'+esc(a.arm.toUpperCase())+'</strong><div class="n">'+n(a.wins)+' / '+n(a.wins+a.losses)+'</div><small>Paper directional wins / settled eligible trades</small><p>'+n(a.responded)+' responses · '+n(a.trades)+' entries · Brier '+(a.brier==null?'—':Number(a.brier).toFixed(4))+'</p><small>Avg latency '+(a.latency_ms==null?'—':Math.round(a.latency_ms)+' ms')+'</small></div>').join('');
document.getElementById('rows').innerHTML=x.recent.map(r=>'<tr>'+[r.round_id,r.arm,r.status,r.p_up==null?'—':Number(r.p_up).toFixed(3),r.action,r.result,r.correct==null?'—':r.correct?'YES':'NO'].map(y=>'<td>'+esc(y)+'</td>').join('')+'</tr>').join('');document.getElementById('time').textContent=(x.demoMode?'⚠ FIXTURE ONLY / NO LIVE DATA · ':'Live local database · ')+'Updated '+x.generatedAt;}catch(e){document.getElementById('time').textContent='Dashboard read error: '+e.message;}}
async function research(){try{const r=await(await fetch('/api/research',{cache:'no-store'})).json();const cards=[['Provider contracts',r.providers||'—'],['Payout',r.payout||'—'],['Pattern Lab V1',r.patternLab||'—'],['Pattern Lab V2',r.patternLabV2||'—'],['Pattern Nodes',r.patternNodes||'—'],['Pattern discovery',r.patterns||'—'],['History',r.history||'—'],['P11 live',r.p11||'—'],['P12',r.p12||'—']];document.getElementById('research').innerHTML=cards.map(y=>'<div class="card"><small>'+esc(y[0])+'</small><div style="font-size:14px">'+esc(y[1])+'</div></div>').join('');}catch{}}
load();setInterval(load,5000);research();setInterval(research,15000);
</script></body></html>`;
export function researchStatus(){const d=readJsonSafe('research/patterns/discovery.json');const m=readJsonSafe('research/history/manifest.json');const v2=readJsonSafe('research/payout/verification-v2.json');const sc=readJsonSafe('data/reports/pattern-lab-v1-scorecard.json');return {
  providers:'LIVE (P11 20r + P12 100r; OpenAI/Jev abstain, GLiDE acts; see reports)',
  payout: v2?`PARTIAL (n=${v2.n}, direction ${v2.directionMatch}/${v2.n}; feeAmount unverified; PnL NULL)`:'PARTIAL (formula reproduced, on-chain fee unverified; PnL NULL)',
  patternLab: sc?`V1 HISTORICAL RESEARCH — NOT A LIVE SIGNAL (chosen ${sc.chosen}; TEST ${sc.test.acted} acted; verdict NO_SIGNAL)`:'Pattern Lab V1: see reports (historical research, not a live signal)',
  patternLabV2: (()=>{try{const s=JSON.parse(fs.readFileSync('data/reports/pattern-lab-v2-r-scorecard.json','utf8'));return `V2 REPLICATION — NOT A LIVE SIGNAL (R:${s.test.acted} acted; M: no eligible config; verdict REPLICATION_NULL)`;}catch{return 'Pattern Lab V2: see reports';}})(),
  patternNodes: 'NODES V1 REPLAY — NOT A LIVE SIGNAL (1566 replayed; B 36/86; NN 410/760; pipeline validated, no edge claimed)',
  patterns: d?`DESCRIPTIVE_ONLY (n=${d.splits.train+d.splits.validation+d.splits.test}, gated test regimes: ${d.gatedTest.length}; no edge claimed)`:'skeleton only',
  history: m?`VENUE_RECORDED ${m.rounds.ok}/${m.rounds.ok+m.rounds.missing} rounds + ${m.prices.ok} prices (isolated var/history)`:'not harvested',
  p11:'PASS_DIRECTIONAL_ONLY (20 rounds; 0 edge; see P11 report)',
  p12:'COMPLETE (100 rounds, NO_DETECTABLE_SIGNAL; see P12 report)'};}
export function serve(cfg){const server=http.createServer((req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='GET'){res.writeHead(405);res.end();return;}if(req.url==='/api/research'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(researchStatus()));return;}if(req.url==='/api/stats'){const s=new Store(cfg.dataDir);const x=s.stats();s.close();res.setHeader('Content-Type','application/json');res.end(JSON.stringify(x));return;}if(req.url==='/'||req.url==='/index.html'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);return;}res.writeHead(404);res.end();});server.listen(cfg.dashboardPort,'127.0.0.1',()=>console.log('Local dashboard: http://127.0.0.1:'+cfg.dashboardPort));return server;}
